"""Initial schema with carbon and emission factors

Revision ID: 14f5b9a4795f
Revises: 
Create Date: 2026-06-19 14:29:26.910040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f5b9a4795f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('carbon_calculated', sa.Float(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_entries_id'), 'carbon_entries', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_entries_user_id'), 'carbon_entries', ['user_id'], unique=False)
    op.create_table('emission_factors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_category'), 'emission_factors', ['category'], unique=False)
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_category'), table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_carbon_entries_user_id'), table_name='carbon_entries')
    op.drop_index(op.f('ix_carbon_entries_id'), table_name='carbon_entries')
    op.drop_table('carbon_entries')
    # ### end Alembic commands ###
