"""Add new features

Revision ID: 8205d672c601
Revises: 9b88af4d5611
Create Date: 2026-06-21 22:10:34.698285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8205d672c601'
down_revision: Union[str, None] = '9b88af4d5611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculator_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('carbon_produced_kg', sa.Float(), nullable=False),
    sa.Column('money_spent', sa.Float(), nullable=False),
    sa.Column('eco_alternative_savings_kg', sa.Float(), nullable=False),
    sa.Column('eco_alternative_savings_money', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculator_entries_id'), 'calculator_entries', ['id'], unique=False)
    op.create_index(op.f('ix_calculator_entries_user_id'), 'calculator_entries', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('routine_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('estimated_carbon_kg', sa.Float(), nullable=False),
    sa.Column('transport_impact', sa.Float(), nullable=False),
    sa.Column('electricity_impact', sa.Float(), nullable=False),
    sa.Column('food_impact', sa.Float(), nullable=False),
    sa.Column('other_impact', sa.Float(), nullable=False),
    sa.Column('eco_score', sa.Float(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_analyses_id'), 'routine_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_routine_analyses_user_id'), 'routine_analyses', ['user_id'], unique=False)
    op.add_column('emission_factors', sa.Column('cost_per_unit', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('goal_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'goal_type')
    op.drop_column('emission_factors', 'cost_per_unit')
    op.drop_index(op.f('ix_routine_analyses_user_id'), table_name='routine_analyses')
    op.drop_index(op.f('ix_routine_analyses_id'), table_name='routine_analyses')
    op.drop_table('routine_analyses')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_calculator_entries_user_id'), table_name='calculator_entries')
    op.drop_index(op.f('ix_calculator_entries_id'), table_name='calculator_entries')
    op.drop_table('calculator_entries')
    # ### end Alembic commands ###
