"""Add activity column to carbon entries

Revision ID: a295877064f9
Revises: 14f5b9a4795f
Create Date: 2026-06-19 14:32:00.830427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a295877064f9'
down_revision: Union[str, None] = '14f5b9a4795f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carbon_entries', sa.Column('activity', sa.String(), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carbon_entries', 'activity')
    # ### end Alembic commands ###
